load "../constants.rb"
pod_net_cidr = "10.244.0.0/16"
MASTER_IP = "192.168.68.10"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = LOCKED_BOX_VERSION
  config.vm.box_check_update = false
  config.vm.hostname = "master"
  config.vm.network :private_network, ip: MASTER_IP
  config.vm.provider "virtualbox" do |vb|
    # In Feb 2022 kubeadm init REQUIRED 1700MB.
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "../provision_kube_node.sh", args: MASTER_IP
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo kubeadm init --pod-network-cidr=#{pod_net_cidr} --apiserver-advertise-address=#{MASTER_IP} --apiserver-cert-extra-sans=#{MASTER_IP} --node-name $(hostname -s)
    # These 3 were pulled from a previous kubeadm init output, and have been stable
    # requirements since Feb 2021:
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

    kubeadm token create --print-join-command > /vagrant/join.sh

    echo 'source <(kubectl completion bash)' >>/home/vagrant/.bashrc
    echo 'alias k=kubectl' >>/home/vagrant/.bashrc
    echo 'complete -F __start_kubectl k' >>/home/vagrant/.bashrc

    wget -q https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    /vagrant/flannel_ifacer.py enp0s8
    kubectl apply -f kube-flannel.yml
  SHELL
end